source = ./sources/values.conf

general{
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
    fail_timeout = 2000
}

animation{
    bezier = quick, 0.7, 0.9, 0.1, 1.0
    animation = fadeIn, 1, 4, quick
    animation = fadeOut, 1, 2, quick
}

background{
    monitor =
    path = screenshot
 
    blur_size = $blur_size
    blur_passes = $blur_passes
    vibrancy = $vibrancy
    vibrancy_darkness = $vibrancy_darkness
    noise = $noise
    contrast = $contrast
}

shape{
    monitor = eDP-1
    size = 25%, 400

    color = rgba(1D1C1B80)
    rounding = $rounding

    border_size = $borders
    border_color = $active_border

    position = 0, 0
    halign = center
    valign = center
}

label{
    monitor = eDP-1
    size = 25%, 12

    font_size = 12
    font_family = DejaVu Sans Mono
    color = $white
    
    text = cmd[update:0] echo "<b>Locked at:</b> $(date +"%b %d - %T")"
    text_align = right
 
    position = -37.5%, -215
    halign = right
    valign = center
}

label{
    monitor = eDP-1
    size = 25%, 12

    font_size = 12
    font_family = DejaVu Sans Mono
    color = $white

    text = <b>Attempts:</b> $ATTEMPTS
    text_align = right
 
    position = -37.5%, -235
    halign = right
    valign = center
}

label{
    monitor = eDP-1
    size = 20%, 100

    font_size = 100
    font_family = DejaVu Sans Mono
    color = $white
   
    text = $TIME
    text_align = center

    position = 0, 80
    halign = center
    valign = center
}

label{
    monitor = eDP-1
    size = 20%, 100

    font_size = 18
    font_family = DejaVu Sans Mono
    color = $white

    text = cmd[update:1000] date "+%A %B %d"
    text_align = center

    position = 0, -10
    halign = center
    valign = center
}

label{
    monitor = eDP-1
    size = 15%, 18
    
    font_size = 18
    font_family = DejaVu Sans Mono
    color = $white

    text =  $USER
    text_align = left

    position = 0, -80
    halign = center
    valign = center
}

input-field{
    monitor = eDP-1
    size = 10%, 35

    outline_thickness = 0
    
    inner_color = $black
    check_color = $white
    fail_color = $warning

    font_color = $white
    fade_on_empty = false
    rounding = $rounding

    position = 0, -130
    halign = center
    valign = center

    fade_on_empty = false
    fade_timeout = 500

    placeholder_text = 
    fail_text = $FAIL <b>($ATTEMPTS)</b>

    swap_font_color = true
}
