source = ./sources/values.conf

general{
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
    fail_timeout = 2000
}

background{
    monitor =
    path = screenshot
 
    blur_size = $blur_size
    blur_passes = $blur_passes
    vibrancy = $vibrancy
    vibrancy_darkness = $vibrancy_darkness
    noise = $noise
    contrast = $contrast
}

shape{
    monitor =
    size = 25%, 350

    color = rgba(14141e80)
    rounding = $rounding

    position = 0, 0
    halign = center
    valign = center
}

label{
    monitor = 
    size = 25%, 12

    font_size = 12
    font_family = DejaVu Sans Mono
    
    text = cmd[update:0] echo "<b>Locked at:</b> $(date +"%b %d - %T")"
    text_align = right
 
    position = -37.5%, -190
    halign = right
    valign = center
}

label{
    monitor = 
    size = 25%, 12

    font_size = 12
    font_family = DejaVu Sans Mono
    
    text = <b>Attempts:</b> $ATTEMPTS
    text_align = right
 
    position = -37.5%, -210
    halign = right
    valign = center
}

label{
    monitor = 
    size = 20%, 100

    font_size = 100
    font_family = DejaVu Sans Mono
    
    text = $TIME
    text_align = center

    position = 0, 60
    halign = center
    valign = center
}

label{
    monitor = 
    size = 15%, 18
    
    font_size = 18
    font_family = DejaVu Sans Mono

    text =  $USER
    text_align = left

    position = 0, -70
    halign = center
    valign = center
}

input-field{
    monitor =
    size = 10%, 35

    outline_thickness = 0
    
    inner_color = $black
    check_color = $blue
    fail_color = $warning

    font_color = $white
    fade_on_empty = false
    rounding = $rounding

    position = 0, -110
    halign = center
    valign = center

    fade_on_empty = false
    fade_timeout = 500

    placeholder_text = 
    fail_text = $FAIL <b>($ATTEMPTS)</b>

    swap_font_color = true
}
