# Insert a blank line between shell prompts
add_newline = true

scan_timeout = 2000
# Define the order and format of the information in our prompt
format = """\
[ ](fg:#F1E4D0)\
[ 󰣇 ](fg:#b3640b bg:#F1E4D0)\
${custom.icon_separator}${custom.icon_separator_no_conda}\
$conda\
$directory\
${custom.directory_separator_not_git}\
${custom.directory_separator_git}\
$symbol($git_branch[](fg:#EAD91F))\
$symbol( $git_commit$git_status$git_metrics$git_state)$fill$cmd_duration$all\
${custom.git_config_email}
$character"""

# Fill character (empty space) between the left and right prompt
[fill]
symbol = " "

# Disable the line break between the first and second prompt lines
[line_break]
disabled = true

[character]
success_symbol = '  [󱞩](fg:#F1E4D0)'
error_symbol = '  [󱞩](fg:#F2412A)'

[custom.icon_separator]
command = ""
format = "[](fg:#F1E4D0 bg:#4d7503)"
when = "test -n \"$CONDA_DEFAULT_ENV\""

[custom.icon_separator_no_conda]
command = ""
format = "[](fg:#F1E4D0 bg:#89847d)"
when = "test -z \"$CONDA_DEFAULT_ENV\""

[conda]
format = '[ $symbol$environment ]($style)[](fg:#4d7503 bg:#89847d)'
symbol = " "
style = "fg:#F1E4D0 bg:#4d7503"

# Customize the format of the working directory
[directory]
truncate_to_repo = true
format = "[ $path ]($style)"
style = "fg:#F1E4D0 bg:#89847d"

[git_branch]
symbol = " "
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:#1D1C1A bg:#EAD91F"

[git_metrics]
disabled = false

[nodejs]
format = "[$symbol($version )]($style)"
style = "fg:#1D1C1A bg:#EAD91F"

[package]
disabled = true # Enable to output the current working directory's package version
format = "[$symbol$version]($style) "
display_private = true

# Output the command duration if over 2 seconds
[cmd_duration]
min_time = 2_000
format = "[   $duration ]($style)"
style = "white"

# Customize the battery indicator
[battery]
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = '#F2412A'

# Output the current git config email address
[custom.git_config_email]
description = "Output the current git user's configured email address."
command = "git config user.email"
format = "\n [$symbol ( $output)]($style)"
# Only when inside git repository
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
style = "text"

# Output a styled separator right after the directory when inside a git repository.
[custom.directory_separator_git]
description = "Output a styled separator right after the directory when inside a git repository."
command = ""
format = "[](fg:#89847d bg:#EAD91F)"
# Only when inside git repository
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"

# Output a styled separator right after the directory when NOT inside a git repository.
[custom.directory_separator_not_git]
description = "Output a styled separator right after the directory when NOT inside a git repository."
command = ""
format = "[](fg:#89847d)"
# Only when NOT inside a git repository
when = "! git rev-parse --is-inside-work-tree > /dev/null 2>&1"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[rust]
symbol = "󱘗 "
format = '[$symbol($version )]($style)'

[dotnet]
format = '[$symbol($version )]($style)'

[lua]
symbol = " "
format = '[$symbol($version )]($style)'
