hl.on("hyprland.start", function () 
  hl.exec_cmd( "awww-daemon & ~/.config/hypr/scripts/wallpaperSwitcher.sh" )
  hl.exec_cmd( "hyprctl setcursor \"Vmix Cursors\" 18" )
  hl.exec_cmd( "QML2_IMPORT_PATH=/nix/store/h3nbjvrm84vxmn8fs319rbhic2ibq524-qt5compat-6.11.0/lib/qt-6/qml qs -p .config/quickshell/main/shell.qml" )
  hl.exec_cmd( "wl-gammarelay-rs &" )
  hl.exec_cmd( "hyprctl setcursor Vimix-cursors 24" )
  hl.exec_cmd( "hyprpm reload" )
  hl.exec_cmd( "systemctl --user start hyprpolkitagent" )
  hl.exec_cmd( "systemctl --user enable --now hyprsunset.service" )
  hl.exec_cmd( "mpdas" )
  hl.exec_cmd( "pactl load-module module-switch-on-connect" )
  hl.exec_cmd( "[workspace special:main silent; size 1480 960; pseudo] kitty" )
end)
