# https://wiki.hyprland.org/Configuring/Monitors/
monitor = eDP-1, 1920x1080@144, 0x0, 1

# mirror
monitor = HDMI-A-1,preferred,auto,1,mirror, eDP-1

# wacom
# monitor = HDMI-A-1,preferred, 1920x0, 1
# phone
monitor = HEADLESS-66, 720x1650@60, -721x720, 1, transform, 2
# iPad
monitor = HEADLESS-67, 2266x1488@60, 2560x-948, 1

workspace = 1, monitor:eDP-1, persistent:true, default=true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
