plugin {
    hyprexpo {
        columns = 3
        gap_size = $gaps
        bg_col = $black
        workspace_method = first 1

        skip_empty = true

        # Open overview
        bind = SUPER, o, hyprexpo:expo, toggle
    }
    hyprbars {
        # example config
        bar_height = 30
        bar_text_size = 10

        bar_color = $inactive_border
        bar_blur = true

        col.text = $white
        bar_text_font = DejaVu Sans Mono

        bar_part_of_window = false
        bar_precedence_over_border = false
        
        icon_on_hover = true

        bar_padding = 10
        bar_text_align = center
        # hyprbars-button = color, size, on-click
        # hyprbars-button = $warning, 18, 󰖭, hyprctl dispatch killactive, $inactive_border
        # hyprbars-button = $green, 18, 󰊓, hyprctl dispatch fullscreen 1, $inactive_border
        on_double_click = hyprctl dispatch fullscreen 1

        # Only focused window has bar
        windowrule = match:focus false, hyprbars:no_bar true

        # Maximized windows have white bg and always show bar
        windowrule = match:fullscreen_state_internal 1, hyprbars:bar_color $active_border
        windowrule = match:fullscreen_state_internal 1, hyprbars:title_color $black
        windowrule = match:focus false, match:group false, match:fullscreen_state_internal 1, hyprbars:no_bar false
        windowrule = match:focus false, match:group false, match:workspace w[tv1], hyprbars:no_bar false

        # Special workspace, pinned and grupped windows have no bar - even when focused
        windowrule = match:focus true, match:workspace special:main, hyprbars:bar_color $active_border
        windowrule = match:focus true, match:workspace special:main, hyprbars:title_color $black
        windowrule = match:focus true, match:pin true, hyprbars:no_bar true
        windowrule = match:focus true, match:group true, hyprbars:no_bar true
    }
}
