###############
### GENERAL ###
###############
# https://wiki.hyprland.org/Configuring/Keywords/
### Modifiers
$mainMod = SUPER

### Colors
$white = rgba(F1E4D0ff)
$blue = rgba(45CBCEff)
$active_border = rgba(89847d80)
$inactive_border = rgba(1D1C1B80)
$warning = rgba(F2412Aff)
$text = rgba(1D1C1Aff)
$active_shadow = rgba(1D1C1A77)
$inactive_shadow = rgba(1D1C1A22)
$black = rgb(1D1C1B)
$accent = rgb(ead91f)

### Look and feel
$rounding = 3
$gaps = 5
$borders = 1

$blur_size = 3
$blur_passes = 4
$noise = 0.05
$contrast = 0.8
$vibrancy = 0.4
$vibrancy_darkness = 0.3
