###############
### WINDOWS ###
###############¸
# specialWorkspace
windowrule = match:workspace special:main, border_size 2
windowrule = match:workspace special:main, rounding $rounding
windowrule = match:workspace w[tv1], match:float off, no_shadow off

# PINNED RULES
windowrule = match:pin true, border_size $borders
windowrule = match:pin true, no_shadow off
windowrule = match:pin true, border_color $active_border $active_border $active_border
windowrule = match:pin true, opacity 1.0 override 1.0 override

# RIGHT CLICK MENUS
windowrule=match:class ^()$,match:title ^()$, no_blur off
windowrule=match:class ^()$,match:title ^()$, opaque 0

# FULLSCREEN WINDOWS
windowrule=match:fullscreen_state_internal 1, border_size 2

##############
### LAYERS ###
##############
# Fuzzel
layerrule=match:namespace launcher, blur on
layerrule=match:namespace launcher, dim_around on
# dunst
layerrule=match:namespace notifications, blur on
# Quickshell
layerrule=match:namespace quickshell,blur on

layerrule=match:namespace ^hypr.*,no_anim on
layerrule=match:namespace selection,no_anim on
layerrule=match:namespace swww-daemon, no_anim on

layerrule=match:namespace ^.*, ignore_alpha 0.49
